import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} m-0 p-0 box-border flex items-center justify-center h-screen w-screen text-white`}
        style={{ backgroundImage: `url('/bg.jpg')` }}
      >
        {children}
      </body>
    </html>
  );
}
